### PR TITLE
Emit error on invalid environment option

### LINKED ISSUE #39: Throw error if non existing `options.environment` was specified
If `options.environment` was set to non existing key in configuration json, then plugin will silently fail and give back unexpected config value, that includes all existing environments. See https://github.com/ajwhite/gulp-ng-config/blob/develop/gulp-ng-config.js#L65

It would be better to throw an error, so that build could exit with non-zero code if incorrect environment was specified. Alternatively this can be made optional, so that it throws only if `options.thrownOnBadEnviroment` or something like that. is set.

What do you think about it?

### PR DESCRIPTION
**Pull request by NickAb**
Fixes #39 

I tried to write a unittest for this one, but I'm relativly new to node and staff, so there is some problem. Here is a code:
`expect(spy).to.have.been.called();` reports that it was not called, but if I replace  `.on('error', spy);` with `gutil.log`, then I can see that `gutil.log` does get called.

```js
    it('should emit an error if an environment key is supplied and the key does not exists', function () {
      var stream = gulp.src(path.normalize(__dirname + '/mocks/input_3.json')),
          spy = chai.spy();
      expect(function () {
        stream.pipe(plugin('gulp-ng-config', {
          environment: 'env'
        })).on('error', spy);
      }).to.not.throw(Error);
      expect(spy).to.have.been.called();
    });

```

### CODE REVIEW

**Comment by ajwhite** [comment]
That is weird, you might need to do

```js
function handler () {
  spy();
}
 stream.pipe(plugin('gulp-ng-config', {
          environment: 'env'
        })).on('error', handler);
```

The callback may become bound do a different context and do weird things.

You know, kinda like this scenario:
```js
function Something() {
  this.foo = 'bar';
}

Something.prototype.handleAction = function () {
  console.log(this.foo);
};

var something = new Something();

eventSource.on('action', something.handleAction);
// this will console.log `undefined`
// versus:
eventSource.on('action', something.handleAction.bind(something))
// this will console.log `bar`
```

**Comment by NickAb** [comment]
I have added a working unittest, it solves the problem that I had with spy not being called.
The problem was with expects not being called synchronously, so `expect(spy)` was called before `pipe(plugin('gulp-ng-config' ...` was able to complete. But there must be a better way to do this, than I did. Any help will be appreciated.

File: test/stream.js [hunk 1]
```diff
@@ -238,20 +236,30 @@ describe('gulp-ng-config', function () {
...
+        stream.pipe(plugin('gulp-ng-config', {
+          environment: 'env'
+        })).on('error', function () {
+          spy();
+          this.emit('end');
+        }).on('end', function () {
+          expect(spy).to.have.been.called();
+          done();
+        }).pipe(through.obj(function () {
+          done();
```
Comment (ajwhite) [inline test/stream.js]: Is this `done` necessary when we have the one above on the `end` handler?

**Comment by ajwhite** [comment]
Sure thing, I can try to take a look tomorrow or this week

File: test/stream.js (hunk 1 above)
Comment (NickAb) [inline test/stream.js]: Yes, as the `end` handler is called explicitly in `error` handler, but does not get called when there is no error emitted by plugin, i.e. when the functionality does not work as intended.

Comment (ajwhite) [inline test/stream.js]: Shouldn't this test verify one or the other here, rather than having both `done` statements?

Comment (NickAb) [inline test/stream.js]: If there is no second `done` and plugin does not emit error on bad environment, then test will throw with timeout. At least that is what was happening on my setup (Windows + very old Node.js). I will take a look on updated setup tomorrow, but it seems that `'end'` event is not emitted properly.

**Comment by ajwhite** [comment]
Sorry for the delay merging this. I really appreciate the contribution! I've taken care of the conflicts that had come up. This will be part of the next release :+1:

**Comment by NickAb** [comment]
Thanks
